Server/Server/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rest_framework.schemas import get_schema_view
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'home_app'

schema_view = get_schema_view(title='Secure Personal Cloud')

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('accounts/signup/', views.signup_view, name='signup'),
    path('accounts/login/', views.login_view, name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('admin/', admin.site.urls),
    path('user/<str:username>/', include('user.urls')),
    path('api-login/', include('rest_framework.urls')),
    path('schema/', schema_view),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Server/user/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls.static import static
from . import views
from django.conf import settings

app_name = 'user'

urlpatterns = [
    path('list/', views.DirFileList.as_view(), name='dir_file_list'),
    path('datalist/', views.DirFileDataList.as_view(), name='dir_file_data_list'),
    path('status/<path:dir_path>', views.DirStatus.as_view(), name='dir_status'),
    path('details/<path:file_path>', views.DirFileDetail.as_view(), name='dir_file_view'),
    path('data/<path:file_path>', views.DirFileData.as_view(), name='dir_file_data_view'),
    # path('users/', views.UserList.as_view()),
    path('userdata/', views.UserDetail.as_view()),
    path('', views.user_home, name='user_home'),
    path('tree/', views.tree_view, name='tree_view'),
    path('<int:pk>/', views.dir_view, name='dir_view'),
    path('islocked/', views.is_locked, name='is_locked'),
    path('lockit/', views.lock_it, name='lock_it'),
    path('unlockit/', views.unlock_it, name='unlock_it'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns = format_suffix_patterns(urlpatterns)

Server/user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


class DirFile(models.Model):
    # Basic File Details

    name = models.CharField(max_length=5000)
    file_type = models.CharField(max_length=20)
    modified_time = models.DateTimeField(auto_now=True)
    encryption_scheme = models.CharField(max_length=100)
    b2code = models.TextField()
    file_path = models.TextField()
    parent_id = models.PositiveIntegerField()

    # User Details , to be changed for file sharing
    # related name is name with which the other model calls this model
    owners = models.ManyToManyField('auth.User', related_name='dirfiles')
    last_update_by = models.CharField(max_length=5000)
    locked = models.BooleanField(default=False)
    lock_time = models.DateTimeField(auto_now_add=True, editable=True)

    # File Contents , to be changed for block level encryption
    # make sure data stored here is always in Base64 encoding
    file_contents = models.TextField()

    # define the string view of the model instances
    def __str__(self):
        name = str(self.name)
        file_type = str(self.file_type)
        encryption_scheme = str(self.encryption_scheme)
        res = "Name : " + name + " Type : " + file_type + " Scheme : " + encryption_scheme
        return res

Server/user/views.py
from django.shortcuts import render
from .models import DirFile
from .serializers import DirFileDetailSerializer, UserSerializer, DirFileDataSerializer, DirStatusSerializer
from rest_framework import generics
from django.contrib.auth.models import User
from rest_framework import permissions
from .permissions import IsOwnerOrReadOnly
from django.contrib.auth.decorators import login_required
from rest_framework.response import Response
from rest_framework import status
from django.utils import timezone
from django.http import HttpResponse
from datetime import timedelta
# Create your views here.


# class based view to view list of all the files owned by a user
# Create new Files and Directories <-Main Use
class DirFileList(generics.ListCreateAPIView):
    # setting the basic queryset and serializer
    queryset = DirFile.objects.all()
    serializer_class = DirFileDetailSerializer
    permission_classes = (permissions.IsAuthenticated, IsOwnerOrReadOnly,)

    def perform_create(self, serializer):
        # serializer.save(owners=User.objects.filter(username__exact=self.request.user.username))
        serializer.save(last_update_by=self.request.user.username)

    def get_queryset(self):
        queryset = self.queryset
        return queryset.filter(owners__pk=self.request.user.pk)


# class based view to view update or delete file instances
# File handling and File end point<- Main Use
class DirFileDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = DirFile.objects.all()
    serializer_class = DirFileDetailSerializer
    permission_classes = (permissions.IsAuthenticated, IsOwnerOrReadOnly,)
    # changing lookup fields according to the path
    lookup_field = 'file_path'
    lookup_url_kwarg = 'file_path'

    def get_queryset(self):
        queryset = self.queryset
        return queryset.filter(owners__pk=self.request.user.pk)

    def destroy(self, request, *args, **kwargs):
        obj = self.get_object()
        instance = self.get_queryset().filter(file_path__startswith=obj.file_path)
        self.perform_destroy(instance)
        return Response(status=status.HTTP_204_NO_CONTENT)


# class based view to view list of all the files owned by a user (DATA Included)
# Create new Files and Directories <-Main Use
class DirFileDataList(generics.ListCreateAPIView):
    # setting the basic queryset and serializer
    queryset = DirFile.objects.all()
    serializer_class = DirFileDataSerializer
    permission_classes = (permissions.IsAuthenticated, IsOwnerOrReadOnly,)

    def perform_create(self, serializer):
        # serializer.save(owners=User.objects.filter(username__exact=self.request.user.username))
        serializer.save(last_update_by=self.request.user.username)

    def get_queryset(self):
        queryset = self.queryset
        return queryset.filter(owners__pk=self.request.user.pk)


# class based view to view update or delete file instances (DATA Included)
# File handling and File end point<- Main Use
class DirFileData(generics.RetrieveUpdateDestroyAPIView):
    queryset = DirFile.objects.all()
    serializer_class = DirFileDataSerializer
    permission_classes = (permissions.IsAuthenticated, IsOwnerOrReadOnly,)
    # changing lookup fields according to the path
    lookup_field = 'file_path'
    lookup_url_kwarg = 'file_path'

    def get_queryset(self):
        queryset = self.queryset
        return queryset.filter(owners__pk=self.request.user.pk)

    def destroy(self, request, *args, **kwargs):
        obj = self.get_object()
        instance = self.get_queryset().filter(file_path__startswith=obj.file_path)
        self.perform_destroy(instance)
        return Response(status=status.HTTP_204_NO_CONTENT)


# # Listing all the users
# # Debugging purposes
# class UserList(generics.ListAPIView):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer


# Details of a particular user
# Can use it for user home page <- Main Use
class UserDetail(generics.RetrieveAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    permission_classes = (permissions.IsAuthenticated,)
    lookup_field = 'username'
    lookup_url_kwarg = 'username'


class DirStatus(generics.ListAPIView):
    queryset = DirFile.objects.all()
    serializer_class = DirStatusSerializer
    permission_classes = (permissions.IsAuthenticated, IsOwnerOrReadOnly,)

    def get_queryset(self):
        queryset = self.queryset
        dir_path = self.kwargs['dir_path']
        queryset = queryset.filter(file_path__startswith=dir_path)
        return queryset.filter(owners__pk=self.request.user.pk)


# Create your views here.
@login_required(login_url="/accounts/login/")
def user_home(request, username):
    if not request.user.username == username:
        return render(request, 'invalid.html', status=status.HTTP_403_FORBIDDEN)
    res_docs = DirFile.objects.filter(owners__pk=request.user.pk).filter(parent_id__exact=0)
    context = {'files': res_docs}
    return render(request, 'userhome.html', context)


def dfs(node, current_user_pk, tab):
    if not node.file_type == 'inode/directory':
        return " " * tab + "|\n" + " " * tab + "|___ " + node.name + "\n"
    else:
        children = DirFile.objects.filter(owners__pk=current_user_pk).filter(parent_id__exact=node.id)
        children = [c for c in children]
        res_str = " " * tab + "|\n" + " " * tab + "|___ " + node.name + "\n"
        for c in children:
            res_str = res_str + dfs(c, current_user_pk, tab + 6)
        return res_str


@login_required(login_url="/accounts/login/")
def tree_view(request, username):
    if not request.user.username == username:
        return render(request, 'invalid.html', status=status.HTTP_403_FORBIDDEN)
    res_docs = DirFile.objects.filter(owners__pk=request.user.id).filter(parent_id__exact=0)
    res_docs = [r for r in res_docs]
    result = ""
    while not len(res_docs) == 0:
        node = res_docs.pop(0)
        cur = dfs(node, request.user.pk, 0)
        result = result + cur
    context = {'resstring': result}
    return render(request, 'treeviewpage.html', context)


@login_required(login_url="/accounts/login/")
def dir_view(request, pk, username):
    if not request.user.username == username:
        return render(request, 'invalid.html', status=status.HTTP_403_FORBIDDEN)
    cur_dir = DirFile.objects.filter(owners__pk=request.user.id).get(id=pk)
    if cur_dir.file_type == 'inode/directory':
        res_docs = DirFile.objects.filter(owners__pk=request.user.id).filter(parent_id__exact=pk)
        dir_name = cur_dir.name
        context = {'files': res_docs, 'dir': dir_name}
        return render(request, 'directorypage.html', context)
    else:
        file_name = cur_dir.name
        file_data = cur_dir.file_contents
        file_type = cur_dir.file_type
        if file_type[:4] == 'text':
            file_type = 'text/plain'
        context = {'file_name': file_name, 'file_data': file_data, 'file_type': file_type}
        return render(request, 'filepage.html', context)
    # else:
        # if cur_dir.encryption_scheme == 'aes':
        #     filename = cur_dir.name
        #     filename = filename[:-6]
        #     # look at this later
        #     filedata = cur_dir.fileContent
        #     # look at this later
        #     filetype = cur_dir.file_type
        #     context = {'file_name': filename, 'file_data': filedata, 'file_type': filetype}
        #     return render(request, 'AESFileview.html', context)


@login_required(login_url="/accounts/login/")
def is_locked(request, username):
    locked_docs = DirFile.objects.filter(owners__pk=request.user.id).filter(locked__exact=True)
    locked_docs = [r for r in locked_docs]
    if len(locked_docs) == 0:
        return HttpResponse("<h2>OK", status=status.HTTP_200_OK)
    else:
        time_max = locked_docs[0].lock_time
        for r in locked_docs:
            if time_max < r.lock_time:
                time_max = r.lock_time
        print(time_max)
        print(timezone.now())
        print(time_max - timezone.now())
        if timezone.now() - time_max > timedelta(seconds=30):
            return HttpResponse("<h2>Time", status=status.HTTP_201_CREATED)
        else:
            return HttpResponse("<h2>Locked", status=status.HTTP_423_LOCKED)


@login_required(login_url="/accounts/login/")
def lock_it(request, username):
    DirFile.objects.filter(owners__pk=request.user.id).update(locked=True)
    DirFile.objects.filter(owners__pk=request.user.id).update(lock_time=timezone.now())
    return HttpResponse('<h2>Locked', status=status.HTTP_200_OK)


@login_required(login_url="/accounts/login/")
def unlock_it(request, username):
    DirFile.objects.filter(owners__pk=request.user.id).update(locked=False)
    return HttpResponse('<h2>Unlocked', status=status.HTTP_200_OK)

Server/user/templates/AESFileview.html
{% extends "basesite.html" %}
{% load static %}
{% block content %}
<h1>{{ file_name }}</h1>
<div>
    <div id="file"></div>
    <div id="img"></div>
    <div id="videofile"></div>
    <div id="music"></div>
    <a href="#" id="downlink" download="{{ file_name }}">
        <button type="button">Download</button>
    </a>

    <script type="text/javascript" src='{% static "aes.js" %}'></script>
    <script type="text/javascript" src='{% static "mode-cfb-min.js" %}'></script>
    <script type="text/javascript" >
        var base64ciphertextFromPython = "{{ file_data }}" ;
        var ciphertext;
        if("{{ file_type }}" == "txt")
        {
            ciphertext = CryptoJS.enc.Utf8.parse(base64ciphertextFromPython);
        }
        else
        {
            ciphertext = CryptoJS.enc.Base64.parse(base64ciphertextFromPython);
        }
        // split iv and ciphertext
        var iv = ciphertext.clone();
        iv.sigBytes = 16;
        iv.clamp();
        ciphertext.words.splice(0, 4); // delete 4 words = 16 bytes
        ciphertext.sigBytes -= 16;

        var key = CryptoJS.enc.Utf8.parse(localStorage['password']);

        // decryption
        var decrypted = CryptoJS.AES.decrypt({ciphertext: ciphertext}, key, {
      iv: iv,
      mode: CryptoJS.mode.CFB
    });
        console.log(decrypted)
        if("{{ file_type }}" == "txt")
        {
            document.getElementById('file').innerHTML = '<embed width=50% src="data:text/html;base64,'+ decrypted.toString(CryptoJS.enc.Utf8) + '"></embed>';
        }
        else if('{{ file_type }}' == 'jpg')
        {
            document.getElementById('img').innerHTML = '<embed witdh=50% src="data:image/jpg;base64,'+btoa(decrypted)+'">'
        }
        else if('{{ file_type }}' == 'png')
        {
            document.getElementById('img').innerHTML = '<embed src="data:image/png;base64,'+decrypted+'">'
        }
        else if('{{ file_type }}' == 'mp4')
        {
            document.getElementById('videofile').innerHTML = '<video id="player" controls >'
            var player = document.getElementById('player');
            player.src = "data:video/webm;base64,"+ btoa(decrypted);
            player.load();
            player.play();
        }

    </script>

</div>
{% endblock %}

Server/user/templates/ARC4Fileview.html
{% extends "basesite.html" %}
{% load static %}
{% block content %}
<h1>{{ file_name }}</h1>
<div>
    <div id="file"></div>
    <div id="image"></div>
    <div id="videofile"></div>
    <div id="musicfile"></div>
     <a href="#" id="downlink" download="{{ file_name }}">
        <button type="button">Download</button>
    </a>
    <script type="text/javascript">
	var ARC4 = function(key){
    var s = new Array(256);
    var s2 = new Array(256);

    for (var i = 0; i < 256; i++){
        s[i] = i;
        s2[i] = key.charCodeAt(i % key.length);
    }

    var j = 0;
    for(var i = 0; i < 256; i++){
        j = (j + s[i] + s2[i]) & 0xff;
        var t = s[i];
        s[i] = s[j];
        s[j] = t;
    }

    this.s = s;
}

ARC4.prototype.encrypt = function(message){
    var i = 0;
    var j = 0;
    var encrypted = [];
    var temp = this.s.slice();

    for(var k = 0; k < message.length; k++){
        var charCode = 0;
        i = (i + 1) & 0xff ;
        j = (j + temp[i]) & 0xff;
        var x = temp[i];
        temp[i] = temp[j];
        temp[j] = x;

        if(message.constructor === Array){
            charCode = message[k];
        } else if (message.constructor === String){
            charCode = message.charCodeAt(k);
        }
        encrypted[k] = (charCode ^ temp[(temp[i] + temp[j]) & 0xff]);
    }
    return encrypted;
}

ARC4.prototype.decrypt = function(message){
    return this.encrypt(message);
}

String.prototype.toBuffer = function(string){
    var buff = [];
    for (var i=0; i < this.length; i++) {
        buff[i] = this.charCodeAt(i);
    }
    return buff;
}

Array.prototype.toString = function(){
    var string = '';
    for (var i=0; i < this.length; i++) {
        string += String.fromCharCode(this[i]);
    }
    return string;
}

Array.prototype.isEqualTo = function(array){
    if(this.length !== array.length){
        return false
    }

    for(var i = 0; i < this.length; i++){
        if(this[i] !== array[i]){
            return false;
        }
    }

    return true;
};
</script>
    <script type="text/javascript" src='{% static "aes.js" %}'></script>
    <script type="text/javascript" src='{% static "mode-cfb-min.js" %}'></script>

    	<script type="text/javascript">
		var key = localStorage['password'];
		var buffer = escape("{{ file_data|safe }}");
		console.log(buffer)
		var cipher = new ARC4(key);
        var decrypted = cipher.decrypt(unescape(buffer));
		console.log("-- Decrypted --");
 		console.log(decrypted);
 		//document.getElementById('fil2').innerHTML = otherBuff;
		if("{{ file_type }}" == "txt")
        {
            document.getElementById('file').innerHTML = '<embed height=50% src="data:text/txt:base64,'+decrypted.toString(CryptoJS.enc.Base64)+'"></embed>';
            document.getElementById('downlink').href = 'data:text/txt;base64,'+ decrypted.toString(CryptoJS.enc.Base64);
        }
        else if('{{ file_type }}' == 'jpg')
        {
            document.getElementById('image').innerHTML = '<embed height=50% width=50% src="data:image/jpg;base64,'+btoa(decrypted)+'"></embed>'
            document.getElementById('downlink').href = 'data:image/jpg;base64,'+ btoa(decrypted);
        }
        else if('{{ file_type }}' == 'png')
        {
            document.getElementById('image').innerHTML = '<embed height=50% src="data:image/png;base64,'+btoa(decrypted)+'"></embed>'
            document.getElementById('downlink').href = 'data:image/png;base64,'+ btoa(decrypted);
        }
        else if('{{ file_type }}' == 'mp4')
        {
            document.getElementById('videofile').innerHTML = '<video id="player" controls >'
            var player = document.getElementById('player');
            player.src = "data:video/webm;base64,"+ btoa(decrypted);
            player.load();
            player.play();
            document.getElementById('downlink').href = 'data:video/webm;base64,'+ btoa(decrypted);
        }
        else if('{{ file_type }}' == 'mp3')
        {
            document.getElementById('musicfile').innerHTML = '<embed src="data:" autostart="true" loop="false" width=50% ></embed>'
        }
	</script>


</div>
{% endblock %}

Server/user/templates/BLOFileview.html
{% extends "basesite.html" %}
{% load static %}
{% block content %}
<h1>{{ file_name }}</h1>
<div>
    <div id="file"></div>
    <div id="img"></div>
    <div id="videofile"></div>
    <div id="music"></div>
    <a href="#" id="downlink" download="{{ file_name }}">
        <button type="button">Download</button>
    </a>
    <script type="text/javascript" src='{% static "aes.js" %}'></script>
    <script type="text/javascript" src='{% static "mode-cfb-min.js" %}'></script>
    <script type="text/javascript" src="http://sladex.org/blowfish.js/ext/blowfish.js">	</script>
	<script type="text/javascript">
		var data = blowfish.decrypt('{{ file_data }}' , localStorage['password'], {cipherMode: 1, outputType: 0}),
		decrypted = data.slice(8,);
        if("{{ file_type }}" == "txt")
        {
            document.getElementById('file').innerHTML = '<embed width=50% src ="data:text/txt;base64,'+ btoa(decrypted)+'">';
            document.getElementById('downlink').href = 'data:text/txt;base64,'+ btoa(decrypted);
        }
        else if('{{ file_type }}' == 'jpg')
        {
            document.getElementById('img').innerHTML = '<embed width=50% src="data:image/jpg;base64,'+btoa(decrypted)+'">'
            document.getElementById('downlink').href = 'data:image/jpg;base64,'+ btoa(decrypted);
        }
        else if('{{ file_type }}' == 'png')
        {
            document.getElementById('img').innerHTML = '<embed src="data:image/png;base64,'+btoa(decrypted)+'">'
            document.getElementById('downlink').href = 'data:image/png;base64,'+ btoa(decrypted);
        }
        else if('{{ file_type }}' == 'mp4')
        {
            document.getElementById('videofile').innerHTML = '<video id="player" controls >'
            var player = document.getElementById('player');
            player.src = "data:video/webm;base64,"+ btoa(decrypted);
            player.load();
            player.play();
            document.getElementById('downlink').href = 'data:video/webm;base64,'+ btoa(decrypted);
        }

    </script>

</div>
{% endblock %}

Server/user/templates/basesite.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
{% block title %}<title>Secure Personal Cloud</title>{% endblock %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<style type="text/css">
	.button {
    background-color: #ffffff; 
    border: none;
    color: black;
    padding: 30px 60px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 20px;
}
</style>

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="http://fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans|Lato|Droid+Serif|Volkhov:400italic|Droid+Sans' rel='stylesheet' type='text/css'>

  <!-- JAVASCRIPT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <script type="text/javascript" language="Javascript" src='{% static "jquery-1.11.3.min.js" %}'></script>

	
</head>
<body background="media/spc.jpg" >
    <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li ><a href="{% url 'homepage' %}">Home</a></li>
          {% if user.is_authenticated %}
            <li>User: <a href="{% url 'user:user_home' user.get_username %}">{{ user.get_username }}</a></li>
            <li><a href="{% url 'logout'%}">Logout</a></li>   
          {% else %}
            <li><a href="{% url 'login'%}">Login</a></li>   
          {% endif %} 
        </ul>
      {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

Server/user/templates/directorypage.html
{% extends "basesite.html" %}

{% block content %}
<h1>{{ dir }}</h1>
<div>
{% if files %}
    <ul>
      {% for f in files %}
        <li><div><p>{{ f.file_type }} <a href="/user/{{ user }}/{{ f.pk }}/">{{ f.name }}</a> </p><p>{{ f.modified_time }}</p></div></li>
      {% endfor %}
    </ul>
    <a href="/user/{{ user }}/tree/" class="button" align="left">Tree View</a>
  {% else %}
    <p>No files are added.</p>
    <a href="/user/{{ user }}/tree/" class="button" align="left">Tree View</a>
  {% endif %}
</div>
{% endblock %}

Server/user/templates/filepage.html
{% extends "basesite.html" %}

{% block content %}
<h1>{{ file_name }}</h1>
<div>
    <div id="text_file"></div>
    <div id="image_file"></div>
    <div id="video_file"></div>
    <div id="music_file"></div>
    <a href="#" id="down_link" download="{{ file_name }}">
        <button type="button">Download</button>
    </a>
    <a href="/user/{{ user }}/tree/" class="button" align="left">Tree View</a>
    <script>
        var decrypted = "{{ file_data }}"
        if( '{{ file_type }}' == 'video/mp4' )
        {
            document.getElementById('video_file').innerHTML = '<video id="player" controls >'
            var player = document.getElementById('player');
            player.src = "data:video/webm;base64,"+ decrypted;
            player.load();
            player.play();
            document.getElementById('down_link').href = 'data:video/mp4;base64,'+ decrypted;
        }
        else
        {
            document.getElementById('text_file').innerHTML = '<embed width=100% height="400" src ="data:' + '{{ file_type }}' + ';base64,'+ decrypted +'">';
            document.getElementById('down_link').href = 'data:' + '{{ file_type }}' + ';base64,'+ decrypted;
        }
    </script>
</div>
{% endblock %}

Server/user/templates/homepage.html
{% extends "basesite.html" %}

{% block content %}
<h1 align="center" style="color: white;">SECURE PERSONAL CLOUD</h1>
<a href="{% url 'signup' %}" class="button" align="left">Signup</a>
<a href="{% url 'login' %}" class="button" style="position: absolute; right: 0; ">Login</a>
{% endblock %}

Server/user/templates/invalid.html
{% extends "basesite.html" %}

{% block content %}
  <p>Invalid attempt to Log in to other account</p>  
  <a href="{% url 'logout'%}">Click here to logout if you wish.</a>
{% endblock %}

Server/user/templates/login.html
{% extends "basesite.html" %}

{% if next %}
  {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
  {% else %}
    <p>Please login to see this page.</p>
  {% endif %}
{% endif %}

{% block content %}
<h1 align="center" style="color: white;">Si Log In!</h1>
<form class="site-form" action="{% url 'login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    {% if requestGET.next%}
    <input type="hidden" name="next" value="{{request.GET.next}}">
    {%endif%}
    <input type="submit" value="Login">
</form>
{% endblock %}

Server/user/templates/logout.html
{% extends "basesite.html" %}

{% block content %}
  <p>Logged out!</p>  
  <a href="{% url 'login'%}">Click here to login again.</a>
{% endblock %}

Server/user/templates/signup.html
{% extends "basesite.html" %}

{% block content %}
<h1 align="center" style="color: white;">Hola SignUp!</h1>
<form class="site-form" action="{% url 'signup' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="SignUp">
</form>
{% endblock %}

Server/user/templates/treeviewpage.html
{% extends "basesite.html" %}

{% block content %}
<h1>All Files</h1>
<div>
{% if resstring %}
    <pre>{{ resstring }}</pre>
    <a href="/user/{{ user }}/tree/" class="button" align="left">Tree View</a>
  {% else %}
    <p>No files are added.</p>
    <a href="/user/{{ user }}/tree/" class="button" align="left">Tree View</a>
  {% endif %}
</div>
{% endblock %}

Server/user/templates/userhome.html
{% extends "basesite.html" %}

{% block content %}
<h1>Hello {{ user }}</h1>
<div id="getpass">
    Please Enter Your Encryption Scheme Password:
    <input type="text" name="passw" id="pass">
    <button type="button" onclick="myFunction()">Submit</button>
</div>
<div id="homeview">
{% if files %}
    <ul>
      {% for f in files %}
        <li><div><p>{{ f.file_type }} <a href="/user/{{ user }}/{{ f.pk }}/">{{ f.name }}</a> </p><p>{{ f.modified_time }}</p></div></li>
      {% endfor %}
    </ul>
    <a href="/user/{{ user }}/tree/" class="button" align="left">Tree View</a>
  {% else %}
    <p>No files are added.</p>
    <a href="/user/{{ user }}/tree/" class="button" align="left">Tree View</a>
  {% endif %}
</div>
<script type="text/javascript">

</script>
<script type="text/javascript">

    //if( localStorage['password'] )
    //{
      //  document.getElementById("getpass").style.display = "none";
    //}
    //else
    //{
        //document.getElementById("homeview").style.display = "none";
    //}
    function myFunction() {
    document.getElementById("getpass").style.display = "none";
    localStorage['password'] = document.getElementById("pass").value;
    document.getElementById("homeview").style.display = "initial";
    console.log(localStorage['password'])
}

</script>
{% endblock %}